name: dev pipeline

on:
  push:
    branches:
      - "develop"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to AWS S3 static site
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::550509277095:role/GithubActions-S3Full
          role-session-name: deploy-to-dev
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Deploy files to S3 static site bucket
        run: aws s3 sync ../dist/ s3://tradehall.app --delete
